language: php
php:
- 7.2
install:
- composer self-update
- composer install --no-interaction
- cp .env.example .env
- source .env
- php artisan key:generate
script: ./vendor/bin/phpunit
env:
  global:
  - APP_ENV=testing
